user: xiangjianfeng
repository: xiangjianfeng/post
public_dir: public

timezone: Asia/Shanghai

theme: donob

menu:
  archives: /archives/
  tags: /tags/
  about: /about/

perpage: 7

title: XiangJianfeng
token: de99e315bc22ab16773b1f17cb0f1ec06a1b84b0
