version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/acyort
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn deploy
      - run: ls -all
      - run: pwd
      - run: cd public
      - run: git config user.name "xiangjianfeng"
      - run: git config user.email "i@xiangjianfeng.com"
      - run: git push --force --quiet "https://${E_CODING}@e.coding.net/jue/post.git" master:pages